apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: coffee
  name: coffee-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: coffee
  template:
    metadata:
      labels:
        app: coffee
    spec:
      containers:
      - name: coffee
        image: manmohanmirkar/mycoffee_image:latest
---
apiVersion: v1
kind: Service
metadata:
  name: coffee-deploy
spec:
  type: NodePort
  selector:
    app: coffee
  ports:
      # By default and for convenience, the `targetPort` is set to the same value as the `port` field.
    - port: 80