apiVersion: v1
kind: Service
metadata:
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    # I currently have an alb with ip 10.100.1.8 for the nginx ingress that will work separately
    service.beta.kubernetes.io/azure-load-balancer-ipv4: 10.100.1.10
  name: nginx-service
spec:
  type: LoadBalancer