
apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
  namespace: backnet-cloud-service
spec:
  ports:
  - name: http
    nodePort: 30873
    port: 80
    protocol: TCP
    targetPort: 80
  - name: https
    nodePort: 30874
    port: 443
    protocol: TCP
    targetPort: 443
  selector:
    app: nginx
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
status:
  loadBalancer: {}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ldap-auth
  name: ldap-auth
  namespace: backnet-cloud-service
spec:
  ports:
  - name: http
    port: 8888
    protocol: TCP
    targetPort: 8888
  selector:
    app: ldap-auth
  sessionAffinity: None
  type: LoadBalancer
  externalTrafficPolicy: Local
status:
  loadBalancer: {}
