apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
spec:
  selector:
  matchLabels:
    app: nginx-deployment
  template:
  metadata:
    labels:
      app: nginx-deployment
  spec:
    containers:
    - name: app
      image: nginx:latest
      ports:
      - name: http
        containerPort: 80
        protocol: TCP